import type { AWS } from '@serverless/typescript';

const serverlessConfiguration: AWS = {
  service: 'dynamodb-example',
  useDotenv: true,
  variablesResolutionMode: '20210219',
  configValidationMode: 'warn',
  frameworkVersion: '*',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
      forceExclude: ['aws-sdk', 'sqlite3'],
      exculdeFiles: './src/modules/**/services/**/*.spec.ts',
    },
    apiGatewayTags: {
      Owner: 'mrcarromesa',
      Product: 'DynamoDBExample',
      Service: 'DynamoDBExample',
    },
    profiles: {
      local: 'local',
      dev: 'dev',
    },
    sharedBucketName: 'lambda-artifacts-123409abdvlgf',
  },

  plugins: [
    'serverless-webpack',
    'serverless-offline',
    'serverless-dotenv-plugin',
  ],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    region: 'us-east-1',
    profile: "${self:custom.profiles.${env:stage, 'dev'}, 'default'}",
    deploymentBucket: {
      blockPublicAccess: true, // Prevents public access via ACLs or bucket policies. Default is false
      skipPolicySetup: false, // Prevents creation of default bucket policy when framework creates the deployment bucket. Default is false
      // Pelo visto o bucket precisa existir previamente antes de realizar o deploy, ou seja criar o bucket manualmente
      name: '${self:custom.sharedBucketName}', // Deployment bucket name. Default is generated by the framework
      maxPreviousDeploymentArtifacts: 10, // On every deployment the framework prunes the bucket to remove artifacts older than this limit. The default is 5
      tags: {
        bucket: 'lambdas-artifacts',
      },
    },
    memorySize: 1536,
    logRetentionInDays: 30,
    versionFunctions: false,
    apiGateway: {
      shouldStartNameWithService: true,
      minimumCompressionSize: 1024,
    },
    apiKeys: [
      {
        name: 'DynamoDBExample',
        value: 'mykeyasdf898asfda90sdfjijklajsdfa9a',
        description:
          'Essa api key é utilizada para acessar o serviço de dynamoDBExample',
      },
    ],
    timeout: 30,
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
  },

  functions: {
    app: {
      tags: {
        function: 'dynamodb-example-app',
      },
      role: 'LambdaRole',
      handler: 'src/server.handler',
      events: [
        {
          http: {
            method: 'get',
            path: '/task',
            private: true,
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'get',
            path: '/task/with-attrs',
            private: true,
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'get',
            path: '/task/{category}/{id}',
            private: true,
            request: {
              parameters: {
                paths: {
                  category: true,
                  id: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'get',
            path: '/task/filter/category/{category}',
            private: true,
            request: {
              parameters: {
                paths: {
                  category: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'get',
            path: '/task/filter/user-created/{user_id}',
            private: true,
            request: {
              parameters: {
                paths: {
                  user_id: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'get',
            path: '/task/filter/user-designated/{user_id}',
            private: true,
            request: {
              parameters: {
                paths: {
                  user_id: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'post',
            path: '/task',
            private: true,
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'put',
            path: '/task/{category}/{id}',
            private: true,
            request: {
              parameters: {
                paths: {
                  category: true,
                  id: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'delete',
            path: '/task/{category}/{id}',
            private: true,
            request: {
              parameters: {
                paths: {
                  category: true,
                  id: true,
                },
              },
            },
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
        {
          http: {
            method: 'delete',
            path: '/task',
            private: true,
            cors: {
              origin: '*',
              maxAge: 86400,
            },
          },
        },
      ],
    },
    trigger_lambda: {
      tags: {
        function: 'dynamodb-example-trigger-lambda',
      },
      handler: 'src/triggersLambda/processTrigger.process',
      events: [
        {
          stream: {
            type: 'dynamodb',
            batchSize: 1,
            startingPosition: 'LATEST',
            arn: {
              'Fn::GetAtt': ['TasksTable', 'StreamArn'],
            },
          },
        },
      ],
    },
  },
  resources: {
    Resources: {
      TasksTable: {
        Type: 'AWS::DynamoDB::Table',
        DeletionPolicy: 'Retain',
        Properties: {
          TableName: 'Tasks',
          TimeToLiveSpecification: {
            AttributeName: 'ttl',
            Enabled: true,
          },
          ProvisionedThroughput: {
            ReadCapacityUnits: 1,
            WriteCapacityUnits: 1,
          },
          // caso for sob demanda remover o ProvisionedThroughput inteiro e adicionar o seguinte:
          // BillingMode: 'PAY_PER_REQUEST',
          StreamSpecification: {
            StreamViewType: 'NEW_IMAGE', // NEW_IMAGE | OLD_IMAGE | NEW_AND_OLD_IMAGES | KEYS_ONLY
          },
          AttributeDefinitions: [
            {
              AttributeName: 'category',
              AttributeType: 'S',
            },
            {
              AttributeName: 'id',
              AttributeType: 'S',
            },
            {
              AttributeName: 'created_by_user_id',
              AttributeType: 'S',
            },
            {
              AttributeName: 'designated_to_user_id',
              AttributeType: 'S',
            },
          ],
          KeySchema: [
            {
              AttributeName: 'category',
              KeyType: 'HASH',
            },
            {
              AttributeName: 'id',
              KeyType: 'RANGE',
            },
          ],
          GlobalSecondaryIndexes: [
            {
              IndexName: 'idx_key_of_created_by_user_id_task',
              Projection: {
                ProjectionType: 'ALL',
              },
              ProvisionedThroughput: {
                WriteCapacityUnits: 5,
                ReadCapacityUnits: 10,
              },
              KeySchema: [
                {
                  KeyType: 'HASH',
                  AttributeName: 'created_by_user_id',
                },
              ],
            },
            {
              IndexName: 'idx_key_of_designated_to_user_id_task',
              Projection: {
                ProjectionType: 'ALL',
              },
              ProvisionedThroughput: {
                WriteCapacityUnits: 5,
                ReadCapacityUnits: 10,
              },
              KeySchema: [
                {
                  KeyType: 'HASH',
                  AttributeName: 'designated_to_user_id',
                },
              ],
            },
          ],
        },
      },
      LambdaRole: {
        Type: 'AWS::IAM::Role',
        Properties: {
          RoleName: 'DynamoDBExample',
          AssumeRolePolicyDocument: {
            Version: '2012-10-17',
            Statement: {
              Effect: 'Allow',
              Principal: {
                Service: ['lambda.amazonaws.com'],
              },
              Action: 'sts:AssumeRole',
            },
          },

          Policies: [
            {
              PolicyName: 'dynamodb-example-policy',
              PolicyDocument: {
                Version: '2012-10-17',
                Statement: [
                  {
                    Effect: 'Allow',
                    Action: [
                      'logs:createLogGroup',
                      'logs:createLogStream',
                      'logs:putLogEvents',
                      'ec2:CreateNetworkInterface',
                      'ec2:DescribeNetworkInterfaces',
                      'ec2:DeleteNetworkInterface',
                    ],
                    Resource: '*',
                  },
                  {
                    Effect: 'Allow',
                    Action: [
                      'dynamodb:GetItem',
                      'dynamodb:PutItem',
                      'dynamodb:DeleteItem',
                      'dynamodb:Scan',
                      'dynamodb:UpdateItem',
                      'dynamodb:DescribeTable',
                      'dynamodb:CreateTable',
                      'dynamodb:BatchWriteItem',
                      'dynamodb:DescribeTimeToLive',
                      'dynamodb:UpdateTimeToLive',
                      'dynamodb:Delete',
                      'dynamodb:Update',
                      'dynamodb:ListStreams',
                    ],
                    Resource: 'arn:aws:dynamodb:us-east-1:*:table/Tasks',
                  },
                ],
              },
            },
          ],
        },
      },
    },
  },
};

module.exports = serverlessConfiguration;
