import type { AWS } from '@serverless/typescript';

const serverlessConfiguration: AWS = {
  service: 'lambdainvoke-example',
  useDotenv: true,
  variablesResolutionMode: '20210219',
  configValidationMode: 'warn',
  frameworkVersion: '*',
  custom: {
    webpack: {
      webpackConfig: './webpack.config.js',
      includeModules: true,
      forceExclude: ['aws-sdk', 'sqlite3'],
      exculdeFiles: './src/modules/**/services/**/*.spec.ts',
    },
    profiles: {
      local: 'local',
      dev: 'dev',
    },
    sharedBucketName: 'lambda-artifacts-123409abdvlgf',
  },

  plugins: [
    'serverless-webpack',
    'serverless-offline',
    'serverless-dotenv-plugin',
  ],
  provider: {
    name: 'aws',
    runtime: 'nodejs12.x',
    region: 'us-east-1',
    profile: "${self:custom.profiles.${env:stage, 'dev'}, 'default'}",
    deploymentBucket: {
      blockPublicAccess: true, // Prevents public access via ACLs or bucket policies. Default is false
      skipPolicySetup: false, // Prevents creation of default bucket policy when framework creates the deployment bucket. Default is false
      // Pelo visto o bucket precisa existir previamente antes de realizar o deploy, ou seja criar o bucket manualmente
      name: '${self:custom.sharedBucketName}', // Deployment bucket name. Default is generated by the framework
      maxPreviousDeploymentArtifacts: 10, // On every deployment the framework prunes the bucket to remove artifacts older than this limit. The default is 5
      tags: {
        bucket: 'lambdas-artifacts',
      },
    },
    memorySize: 1536,
    logRetentionInDays: 30,
    versionFunctions: false,
    apiGateway: {
      shouldStartNameWithService: true,
      minimumCompressionSize: 1024,
    },
    timeout: 30,
    environment: {
      AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1',
    },
  },

  functions: {
    print_string: {
      tags: {
        function: 'lambdainvoke-example-tag',
      },
      role: 'LambdaRole',
      timeout: 300,
      name: 'lambdainvoke-example',
      handler: 'src/invokes/processInvoke.process',
    },
  },
  resources: {
    Resources: {
      LambdaRole: {
        Type: 'AWS::IAM::Role',
        Properties: {
          RoleName: 'lambdainvokeExample',
          AssumeRolePolicyDocument: {
            Version: '2012-10-17',
            Statement: {
              Effect: 'Allow',
              Principal: {
                Service: ['lambda.amazonaws.com'],
              },
              Action: 'sts:AssumeRole',
            },
          },

          Policies: [
            {
              PolicyName: 'lambdainvoke-example-policy',
              PolicyDocument: {
                Version: '2012-10-17',
                Statement: [
                  {
                    Effect: 'Allow',
                    Action: [
                      'logs:createLogGroup',
                      'logs:createLogStream',
                      'logs:putLogEvents',
                      'ec2:CreateNetworkInterface',
                      'ec2:DescribeNetworkInterfaces',
                      'ec2:DeleteNetworkInterface',
                    ],
                    Resource: '*',
                  },
                ],
              },
            },
          ],
        },
      },
    },
  },
};

module.exports = serverlessConfiguration;
